In [1]:
class Animal:
    isalive = True
    age = 0

In [2]:
my_cat = Animal()

In [3]:
print(my_cat)
print(type(my_cat))

<class '__main__.Animal'>


In [4]:
my_cat.isalive

True

In [5]:
my_second_cat = Animal()

In [6]:
my_cat.age == my_second_cat.age

True

In [7]:
my_cat.age = 2

In [8]:
my_cat.age == my_second_cat.age

False

In [9]:
Animal.isalive = False

In [10]:
print(my_cat.isalive)
print(my_second_cat.isalive)

False
False


In [11]:
Animal.isalive = True

In [12]:
class Cat:
    isalive = True
    age = 0
    sound = "meow"

    def __init__(self, location):
        self.location = location.values()

    def aged(self):
        self.age += 1

- packing and unpacking

In [13]:
fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

In [15]:
first, second, *remaning, last = fruits

In [16]:
print(first)
print(last)
print(second)

apple
mango
banana


In [17]:
print(remaning)

['cherry', 'orange', 'kiwi', 'melon']


In [18]:
def my_example(*args):
    return print(args)

In [19]:
my_example(1, 2, 3, 'a', 'b', 'c')

(1, 2, 3, 'a', 'b', 'c')


In [20]:
def my_example(my_number, *args):
    return f"My number is: {my_number}, {args}"

In [21]:
my_example(10, 11, 12)

'My number is: 10, (11, 12)'

In [23]:
def second_example(**kwargs):
    return kwargs

In [24]:
second_example(number_first_number=10, number_second_number=11,)

{'number_first_number': 10, 'number_second_number': 11}

In [26]:
def third_example(special_number=1, **kwargs):
    return f"Special number: {special_number}, Others: {kwargs}"

In [27]:
third_example(special_number=2, number_first_number=10, number_second_number=11,)

"Special number: 2, Others: {'number_first_number': 10, 'number_second_number': 11}"

In [28]:
# def my_function(<positional_args>, *args, <key-word_args>, **kwargs)

## Numpy

In [29]:
number = 15

In [30]:
type(number)

int

In [31]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [32]:
my_list = [1, 2, 3]

In [33]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [34]:
# pip install numpy
# pip3 install numpy

In [35]:
import numpy as np

In [36]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [37]:
array_a = np.array([1, 2, 3, 4])

In [38]:
array_a

array([1, 2, 3, 4])

In [39]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [40]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [41]:
array_a[0]

1

In [42]:
array_b[-1]

2.0

In [ ]:
array_a[:2]

array([1, 2])

In [44]:
array_a.dtype

dtype('int64')

In [45]:
array_b.dtype

dtype('float64')

In [46]:
empty_array = np.array([])

In [47]:
empty_array.dtype

dtype('float64')

In [48]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)